#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500}
PX4_GZ_NO_FOLLOW=1

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.45
param set-default NAV_DLL_ACT 0

param set-default MIS_TAKEOFF_ALT 8.0

param set-default MPC_XY_VEL_I_ACC 0.0
param set-default MPC_XY_P 0.0
param set-default MC_YAW_WEIGHT 0.0
param set-default MC_AIRMODE 0
param set-default MC_ROLLRATE_P 0.05
param set-default MC_PITCHRATE_P 0.05
param set-default MPC_THR_MAX 0.5
param set-default MPC_Z_VEL_I_ACC 0.0
param set-default MPC_LAND_SPEED 2.0
param set-default MPC_Z_VEL_MAX_DN 3.0
param set-default MPC_Z_VEL_P_ACC 4.0
param set-default MPC_Z_VEL_I_ACC 0.5

param set-default FD_FAIL_R 0
param set-default FD_FAIL_P 0

param set-default SYS_FAILURE_EN 1
param set-default CA_FAILURE_MODE 2
