#!/bin/sh
#
# @name Gazebo Typhoon H480
#
# @type Hexarotor x
# @class Copter
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=typhoon_h480}
PX4_GZ_NO_FOLLOW=1

param set-default SIM_GZ_EN 1
param set-default MAV_TYPE 13

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

# Rotor positions: PX4 body frame +Y = right, Gazebo ENU +Y = left.
# CA_ROTOR_PY = -(Gazebo Y position).

# Motor 0: right,       cw
param set-default CA_ROTOR0_PX -0.002
param set-default CA_ROTOR0_PY  0.243
param set-default CA_ROTOR0_KM -0.05

# Motor 1: left,        ccw
param set-default CA_ROTOR1_PX -0.002
param set-default CA_ROTOR1_PY -0.243
param set-default CA_ROTOR1_KM  0.05

# Motor 2: front-left,  cw
param set-default CA_ROTOR2_PX  0.211
param set-default CA_ROTOR2_PY -0.120
param set-default CA_ROTOR2_KM -0.05

# Motor 3: back-right,  ccw
param set-default CA_ROTOR3_PX -0.209
param set-default CA_ROTOR3_PY  0.122
param set-default CA_ROTOR3_KM  0.05

# Motor 4: front-right, ccw
param set-default CA_ROTOR4_PX  0.211
param set-default CA_ROTOR4_PY  0.120
param set-default CA_ROTOR4_KM  0.05

# Motor 5: back-left,   cw
param set-default CA_ROTOR5_PX -0.209
param set-default CA_ROTOR5_PY -0.122
param set-default CA_ROTOR5_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150
param set SIM_GZ_EC_MIN1 150
param set SIM_GZ_EC_MIN2 150
param set SIM_GZ_EC_MIN3 150
param set SIM_GZ_EC_MIN4 150
param set SIM_GZ_EC_MIN5 150
param set SIM_GZ_EC_MIN6 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

param set-default MPC_THR_HOVER 0.35
param set-default MC_AIRMODE 2

param set-default SYS_FAILURE_EN 1
param set-default CA_FAILURE_MODE 1
param set-default NAV_DLL_ACT 0
param set-default MIS_TAKEOFF_ALT 5.0
